app/models.py
from . import db

# define the database models in this file
class Info(db.Model):


    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    password = db.Column(db.String(120), unique=False)

    def __init__(self, username, password):
        self.username = username
        self.password = password

    def __repr__(self):
        return '<id %r>' % self.id

class Text(db.Model):


    id = db.Column(db.Integer, primary_key=True)
    userId = db.Column(db.Integer, unique=False)
    text = db.Column(db.String(255), unique=False)

    def __init__(self, userId, text):
        self.userId = userId
        self.text = text

    def __repr__(self):
        return '<id %r>' % self.id

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from . import config

# use orm tool SQLAlchemy to operate any database, just provide an URL for the database
db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config.ProductionConfig)
    # explicitly assign a static folder for app, useful in blueprint
    app.static_folder = 'static'
    # app.template_folder = 'templates'
    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
import os
import csv
import json
from . import main
from .. import db
from ..models import Info
from flask import current_app as app
from flask import request, session, g, redirect, url_for, abort, \
                render_template, flash, send_from_directory

@main.route('/')
def index():

    return render_template('index.html')



@main.route('/register', methods=['POST'])
def register():
    data = json.loads(request.values.get('data'))
    print(data)
    name = data['name']
    password = data['password']
    user = Info(name, password)
    db.session.add(user)
    db.session.commit()

    return 'success'

@main.route('/login', methods=['POST','GET'])
def login():

    data = json.loads(request.values.get('data'))
    name = data['name']
    password = data['password']
    user = Info.query.filter_by(username=name, password=password).first()
    print(user)
    if user ==None:
        flash('Wrong username/password')
        return "fail"
    else:
        flash('successful')
        # return redirect(url_for('main.index'))
        return "success"


@main.route('/login_html',methods=['POST','GET'])
def login_html():
    return render_template('login.html')

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Home</title>

    <!-- Font Awesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <!-- Line icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">
    <!-- Bootstrap -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Slick slider -->
    <link href="../static/css/slick.css" rel="stylesheet">
    <!-- Gallery Lightbox -->
    <link href="../static/css/magnific-popup.css" rel="stylesheet">
    <!-- Theme color -->
    <!--<link id="switcher" href="../static/css/theme-color/default-theme.css" rel="stylesheet">-->

    <!-- Main Style -->
    <link href="../static/css/style.css" rel="stylesheet">

    <!-- Fonts -->

    <!-- Open Sans for body font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700,800" rel="stylesheet">
    <!-- Montserrat for Title -->
  	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">



    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  	<!-- Start Header -->
	<header id="mu-header" class="" role="banner">
		<div class="container">
			<nav class="navbar navbar-default mu-navbar">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>

		      <!-- Text Logo -->
		      <a class="navbar-brand" href="#">Jinfen_Website</a>

		      <!-- Image Logo -->
		      <!-- <a class="navbar-brand" href="#"><img src="../static/images/logo.png"></a> -->


		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      	<ul class="nav navbar-nav mu-menu navbar-right">
			        <li><a href="#">HOME</a></li>
			        <li><a href="#mu-counter">ABOUT US</a></li>
			        <li><a href="#mu-service">Login</a></li>

		      	</ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
		</div>
	</header>
	<!-- End Header -->

	<!-- Start Featured Slider -->

	<section id="mu-featured-slider">
		<div class="row">
			<div class="col-md-12">
				<div class="mu-featured-slide">

					<!-- Start Single slide -->
					<div class="mu-featured-slider-single gtco-cover gtco-cover-sm">
						<img src="../static/images/bg.jpg" style="-webkit-filter: blur(5px); /* Chrome, Safari, Opera */
    filter: blur(5px); ">
						<div class="mu-featured-slider-content">
							<h1>WELCOME TO EMOTIONS</h1>
							<p>To detect your emotion from text today!</p>
							<a href="#" class="mu-primary-btn">Let's get a try!</a>
						</div>
					</div>
					<!-- End Single slide -->

					<!-- Start Single slide -->
					<div class="mu-featured-slider-single">
						<img src="../static/images/bg.jpg" style="-webkit-filter: blur(5px); /* Chrome, Safari, Opera */
    filter: blur(5px); " >
						<div class="mu-featured-slider-content">
							<h1>Join us</h1>
							<p>Let's connect together and built your own emotion story</p>
							<a href="#" class="mu-primary-btn">Login</a>
							<a href="#" class="mu-primary-btn">Register</a>
						</div>
					</div>
					<!-- End Single slide -->

					<!-- Start Single slide -->
					<div class="mu-featured-slider-single">
						<img src="../static/images/bg.jpg" style="-webkit-filter: blur(5px); /* Chrome, Safari, Opera */
    filter: blur(5px); ">
						<div class="mu-featured-slider-content">
							<h1>Contribute to our System</h1>
							<p>you can build your own model and test them here</p>
							<a href="#" class="mu-primary-btn">Try it</a>
						</div>
					</div>
					<!-- End Single slide -->

				</div>
			</div>
		</div>
	</section>

	<!-- Start Featured Slider -->

	<!-- Start main content -->

	<main role="main">

		<!-- Start About -->


		<!-- Start Counter -->
		<section id="mu-counter" style="background-image: url(../static/images/feature2-image.jpg)">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="mu-counter-area">
							<h2 class="mu-heading-title">SOME FACTS ABOUT US</h2>

							<div class="mu-counter-block">
								<div class="row">

									<!-- Start Single Counter -->
									<div class="col-md-3 col-sm-6">
										<div class="mu-single-counter">
											<i class="icon-like"></i>
											<div class="counter-value" data-count="750">0</div>
											<h5 class="mu-counter-name">Projects Completed</h5>
										</div>
									</div>
									<!-- / Single Counter -->

									<!-- Start Single Counter -->
									<div class="col-md-3 col-sm-6">
										<div class="mu-single-counter">
											<i class="icon-emotsmile"></i>
											<div class="counter-value" data-count="560">0</div>
											<h5 class="mu-counter-name">H..y Clients</h5>
										</div>
									</div>
									<!-- / Single Counter -->

									<!-- Start Single Counter -->
									<div class="col-md-3 col-sm-6">
										<div class="mu-single-counter">
											<i class="icon-cup"></i>
											<div class="counter-value" data-count="1555">0</div>
											<h5 class="mu-counter-name">Cups Consumed</h5>
										</div>
									</div>
									<!-- / Single Counter -->

									<!-- Start Single Counter -->
									<div class="col-md-3 col-sm-6">
										<div class="mu-single-counter">
											<i class="icon-trophy"></i>
											<div class="counter-value" data-count="10">0</div>
											<h5 class="mu-counter-name">Got Awards</h5>
										</div>
									</div>
									<!-- / Single Counter -->

								</div>
							</div>


						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End Counter -->

		<!-- Start Service -->
		<section id="mu-service" style="background-image: url(../static/images/img_bg_1.jpg)" role="banner">
			<div class="container">
				<div class="row">
					<!--<div class="col-md-12">-->
						<div class="mu-service-area">

							<div class="mu-service-header">
								<h2 class="mu-heading-title">Register</h2>
								<span class="mu-header-dot"></span>
								<!--<p>already a user? <a href="{{ url_for('main.login_html') }}" style="text-decoration:underline; color:red">Login</a></p>-->
							<p id="myLogin">already a user? <a id="login_form" style="text-decoration:underline; color:red">Login</a>

							</p>
							</div>

							<!-- Start Service Content -->
							<div class="mu-service-content">
                            <div class="col-md-12 col-md-offset-0 text-left">



						<div class="col-md-4" >
							<div class="form-wrap">
								<div class="tab">

									<div class="tab-content">
										<!--<div class="tab-content-inner active" data-content="signup">-->

											<!--<form role="form" id="formRegister" action="{{url_for('main.register') }}">-->
												<div class="row form-group">

														<label for="name">Your Name</label>
														<input type="text" id="name" class="form-control">



													<div class="col-md-12">
														<label for="password1">Password</label>
														<input type="password" class="password" id="password1" name="password1" >
													</div>


														<!--<label for="password2">Confirm Password</label>-->
                                                        <input type="password" class="password"  id="password2" name="password2" placeholder="confirm">


                                                    <button type="submit" class="mu-send-msg-btn" id="register"><span>SUBMIT</span></button>
                                                    <button type="submit" value="login" class="mu-send-msg-btn" id="login" hidden><span>SUBMIT</span></button>
                                                </div>

											<!--</form>-->
										<!--</div>-->


									</div>
								</div>
							</div>
						</div>



				    </div>
							</div>
							<!-- End Service Content -->

						</div>

					<!--</div>-->
				</div>
			</div>


		</section>
		<!-- End Service -->

		<!-- Start Contact -->
		<section id="mu-contact" class="gtco-cover gtco-cover-sm" role="banner" style="background-image: url(../static/images/img_5.jpg)" data-stellar-background-ratio="0.5">
            <div class="overlay"></div>
			<div class="gtco-container">
				<div class="row">
					<div class="col-md-12">
						<div class="mu-contact-area">

							<div class="mu-contact-header">
								<h2 class="mu-heading-title">Try <span>Emotion</span></h2>
								<span class="mu-header-dot"></span>
							</div>

							<!-- Start Contact Content -->
							<!--<div class="mu-contact-content">-->
								<div class="center">

									<!--<div class="col-md-6">-->


											<form id="ajax-contact" method="post" action="mailer.php" class="form-inline" role="form">

												<div class="form-group">
													<textarea class="form-control" placeholder="Text" id="message" name="message" required style="width:600px; height:300px"></textarea>
												</div>
												<button type="submit" class="mu-send-msg-btn"><span>SUBMIT</span></button>
								            </form>


									<!--</div>-->
                                    <!--<div class="col-md-6">-->


											<form id="ajax-contact2" method="post" action="mailer.php" class="form-inline" role="form">

												<div class="form-group">
													<textarea class="form-control" placeholder="Result" id="result" name="result" required ></textarea>
												</div>

								            </form>


									<!--</div>-->



								</div>
							<!--</div>-->
							<!-- End Contact Content -->

						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End Contact -->



	</main>

	<!-- End main content -->


	<!--&lt;!&ndash; Start footer &ndash;&gt;-->
	<!--<footer id="mu-footer" role="contentinfo">-->
			<!--<div class="container">-->
				<!--<div class="mu-footer-area">-->
					<!--<p>Copyright &copy; 2019.Company name All rights reserved.<a target="_blank" href="http://sc.chinaz.com/moban/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></p>-->
				<!--</div>-->
			<!--</div>-->

	<!--</footer>-->
	<!--&lt;!&ndash; End footer &ndash;&gt;-->



    <!-- jQuery library -->
    <script src="https://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Bootstrap -->
    <script src="../static/js/bootstrap.min.js"></script>
	<!-- Slick slider -->
    <script type="text/javascript" src="../static/js/slick.min.js"></script>
    <!-- Counter js -->
    <script type="text/javascript" src="../static/js/counter.js"></script>
    <!-- Filterable Gallery js -->
    <script type="text/javascript" src="../static/js/jquery.filterizr.min.js"></script>
    <!-- Gallery Lightbox -->
    <script type="text/javascript" src="../static/js/jquery.magnific-popup.min.js"></script>
    <!-- Ajax contact form  -->
    <script type="text/javascript" src="../static/js/ajax_form.js"></script>


    <!-- Custom js -->
	<script type="text/javascript" src="../static/js/custom.js"></script>
	
    
  </body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Home</title>

    <!-- Font Awesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <!-- Line icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">
    <!-- Bootstrap -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Slick slider -->
    <link href="../static/css/slick.css" rel="stylesheet">
    <!-- Gallery Lightbox -->
    <link href="../static/css/magnific-popup.css" rel="stylesheet">
    <!-- Theme color -->
    <!--<link id="switcher" href="../static/css/theme-color/default-theme.css" rel="stylesheet">-->

    <!-- Main Style -->
    <link href="../static/css/style.css" rel="stylesheet">

    <!-- Fonts -->

    <!-- Open Sans for body font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700,800" rel="stylesheet">
    <!-- Montserrat for Title -->
  	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">



    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>







		<!-- Start Service -->
		<section id="mu-service" style="background-image: url(../static/images/img_bg_1.jpg)" role="banner">
			<div class="container">
				<div class="row">
					<!--<div class="col-md-12">-->
						<div class="mu-service-area">

							<div class="mu-service-header">
								<h2 class="mu-heading-title">Login</h2>

							</div>

							<!-- Start Service Content -->
							<div class="mu-service-content">
                            <div class="col-md-12 col-md-offset-0 text-left">



						<div class="col-md-4" >
							<div class="form-wrap">
								<div class="tab">

									<div class="tab-content">
										<!--<div class="tab-content-inner active" data-content="signup">-->

											<!--<form role="form" id="formRegister">-->
												<div class="row form-group">

														<label for="name">Your Name</label>
														<input type="text" id="name" class="form-control">



													<div class="col-md-12">
														<label for="password">Password</label>
														<input type="password" class="password" id="password" name="password" >
													</div>





                                                    <button type="submit" class="mu-send-msg-btn" id="login"><span>Login</span></button>
                                                </div>

											<!--</form>-->
										<!--</div>-->


									</div>
								</div>
							</div>
						</div>



				    </div>
							</div>
							<!-- End Service Content -->

						</div>

					<!--</div>-->
				</div>
			</div>


		</section>
		<!-- End Service -->







	<!-- End main content -->


	<!--&lt;!&ndash; Start footer &ndash;&gt;-->
	<!--<footer id="mu-footer" role="contentinfo">-->
			<!--<div class="container">-->
				<!--<div class="mu-footer-area">-->
					<!--<p>Copyright &copy; 2019.Company name All rights reserved.<a target="_blank" href="http://sc.chinaz.com/moban/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></p>-->
				<!--</div>-->
			<!--</div>-->

	<!--</footer>-->
	<!--&lt;!&ndash; End footer &ndash;&gt;-->



    <!-- jQuery library -->
    <script src="https://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Bootstrap -->
    <script src="../static/js/bootstrap.min.js"></script>
	<!-- Slick slider -->
    <script type="text/javascript" src="../static/js/slick.min.js"></script>
    <!-- Counter js -->
    <script type="text/javascript" src="../static/js/counter.js"></script>
    <!-- Filterable Gallery js -->
    <script type="text/javascript" src="../static/js/jquery.filterizr.min.js"></script>
    <!-- Gallery Lightbox -->
    <script type="text/javascript" src="../static/js/jquery.magnific-popup.min.js"></script>
    <!-- Ajax contact form  -->
    <!--<script type="text/javascript" src="../static/js/ajax_form.js"></script>-->


    <!-- Custom js -->
	<script type="text/javascript" src="../static/js/custom.js"></script>


  </body>
</html>